---
title: "02_Hierchical Clusterin"
author: "Ziwei Crystal Zang"
date: "9/22/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#library packages
for (pkg in c("psych", "ggplot2", "dplyr", "readr", "janitor", "mosaic", "factoextra", "patchwork", "mclust")) {
  library(pkg, character.only = TRUE)
}
```

```{r}
data <- read_csv("/Users/czang/Documents/2020Fall/2079ML/data/Breast_GSE45827.csv") 
data <- data%>%
  clean_names()
colnames(data)
label <- data$type
```


```{r}
#log 
# feature_matrix <- apply(data[,3:ncol(data)], 2, function(x) log(x))
# feature_df <- as.data.frame(feature_matrix)
# feature_id <- colnames(feature_df)
#aov( x1553620_at ~ type, data = data)
# feature_error <- c()
# for(i in 1:length(feature_id)){
# #  feature_i <- as.vector(feature_df[,i])
#   #feature_id_i <- colnames(feature_df)[i]
#   res.aov <- aov( feature_df[[i]] ~ type, data = data)
#   feature_error[i] <- sigma(res.aov)
# }
# 
# feature_error_df <- as.data.frame(cbind(feature_id, feature_error))
# 
# saveRDS(feature_error_df, "/Users/czang/Documents/2020Fall/2079ML/data/feature_error.rds")

```


```{r}
#1. Select features highly correlated with the lable
feature_error_df <- readRDS("/Users/czang/Documents/2020Fall/2079ML/project/BIOST2079/data/feature_error.rds")
feature_error_df$feature_error <- as.numeric(feature_error_df$feature_error)


ggplot(feature_error_df, aes(x = feature_error)) +
  geom_histogram(binwidth = 0.025) + 
  labs(title = "Distribution of feature's Residual Standard Error",x= "residual standard error") +
  theme_bw()


feature <- feature_error_df%>%
  arrange(feature_error)%>%
  top_n(1500)%>%
  pull(feature_id)

#subset data with pre-selected features
data_sub <-  data[,feature]

#2. Log transform
feature_matrix <- apply(data_sub[,3:ncol(data_sub)], 2, function(x) log(x))
feature_df <- as.data.frame(feature_matrix)
feature_id <- colnames(feature_df)

#3. standardize
feature_df_z <- feature_df%>%
  mutate_each_(funs(scale(.) %>% as.vector), vars=feature_id)

#summary(feature_df_z$x205399_at)
```

# Hierchical Cluster

## Dissimilarity Measure: Euclidean Distance
```{r}
matrix <- as.matrix(feature_df_z)
matrix <- t(matrix)
dim(matrix)

# distance between patients
row_distance = dist(matrix, method = "euclidean")

nc_km <- fviz_nbclust(matrix, FUN = kmeans, method = "wss")+
  labs(title ="Optimal number of cluster using K-means")


nc_hcut <-  fviz_nbclust(matrix, FUN = hcut, method = "wss")+
  labs(title ="Optimal number of cluster using Hierchical Clustering")

png("/Users/czang/Documents/2020Fall/2079ML/project/BIOST2079/output/ncluster_comparison.png", res=100)
nc_km + nc_hcut+ plot_layout(ncol=1)
dev.off()


nc_gap_stats_km <-  fviz_nbclust(matrix, FUN = kmeans, method = "gap_stat", nboot = 500, nstart = 25)

saveRDS(nc_gap_stats_km, "/Users/czang/Documents/2020Fall/2079ML/project/BIOST2079/data/nc_gap_stats_km.rds")

nc_gap_stats_hcut <- fviz_nbclust(matrix, FUN = hcut, method = "gap_stat")
saveRDS(nc_gap_stats_hcut, "/Users/czang/Documents/2020Fall/2079ML/project/BIOST2079/data/nc_gap_stats_hcut.rds")


png("/Users/czang/Documents/2020Fall/2079ML/project/BIOST2079/output/ncluster_gapstats_comparison.png", res=100)
nc_gap_stats_km + nc_gap_stats_hcut+ plot_layout(ncol=1)
dev.off()

fviz_nbclust(matrix, FUNcluster = kmeans, method = "silhouette")

fviz_nbclust(matrix, FUNcluster = hcut, method = "silhouette")

```

### Ward
```{r}
# try different linkage
hc.ward = hclust(d = row_distance, method = "ward.D")

png("/Users/czang/Documents/2020Fall/2079ML/project/BIOST2079/output/hierchical_ward_euclidean_10cluster_z.png", width = 1500, height = 1000, res=220)
fviz_dend(
  hc.ward,
  k = 10,
  cex = 0.3,
  palette = "jco",
  color_labels_by_k = TRUE,
  rect = TRUE,
  rect_fill = TRUE,
  rect_border = "jco",
  labels_track_height = 3.5
)
dev.off()

# hc_label<-cutree(hc.ward, k = 3)
# table(hc_label,label)
# adjustedRandIndex(hc_label, label)
```

### Complete
```{r}
hc.complete <- hclust(d = row_distance, method = "complete")

png("/Users/czang/Documents/2020Fall/2079ML/project/BIOST2079/output/hierchical_complete_euclidean_10cluster_z.png", width = 1500, height = 1000, res=220)

fviz_dend(
  hc.complete,
  k = 10,
  cex = 0.2,
  palette = "jco",
  color_labels_by_k = TRUE,
  rect = TRUE,
  rect_fill = TRUE,
  rect_border = "jco",
  labels_track_height = 3.5
)
dev.off()


```

### Average
```{r}
hc.average <- hclust(d = row_distance, method = "average")

png("/Users/czang/Documents/2020Fall/2079ML/project/BIOST2079/output/hierchical_average_euclidean_10cluster_z.png", width = 1500, height = 1000, res=220)

fviz_dend(
  hc.average,
  k = 10,
  cex = 0.2,
  palette = "jco",
  color_labels_by_k = TRUE,
  rect = TRUE,
  rect_fill = TRUE,
  rect_border = "jco",
  labels_track_height = 3
)
dev.off()
```

### Single
```{r}
hc.single <- hclust(d = row_distance, method = "single")
png("/Users/czang/Documents/2020Fall/2079ML/project/BIOST2079/output/hierchical_single_euclidean_4cluster.png", width = 1500, height = 1000, res=220)
fviz_dend(
  hc.single,
  k = 4,
  cex = 0.2,
 # palette = "jco",
  color_labels_by_k = TRUE,
  rect = TRUE,
  rect_fill = TRUE,
  rect_border = "jco",
  labels_track_height = 3
)
dev.off()
```

### Centroid
```{r}
hc.centroid <- hclust(d = row_distance, method = "centroid")

png("/Users/czang/Documents/2020Fall/2079ML/project/BIOST2079/output/hierchical_centroid_euclidean_4cluster.png", width = 1500, height = 1000, res=220)
fviz_dend(
  hc.centroid,
  k = 4,
  cex = 0.2,
  palette = "jco",
  color_labels_by_k = TRUE,
  rect = TRUE,
  rect_fill = TRUE,
  rect_border = "jco",
  labels_track_height = 3
)
dev.off()
```




## Dissimilarity Measure: Pearson correlation
```{r}
matrix <- as.matrix(feature_df_z)
matrix <- t(matrix)

# distance between patients
row_distance_p = get_dist(matrix, method = "pearson")
class(row_distance_p)
```

### Ward
```{r}
# try different linkage
hc.ward = hclust(d = row_distance_p, method = "ward.D")

png("/Users/czang/Documents/2020Fall/2079ML/project/BIOST2079/output/hierchical_ward_pearson_4cluster_z.png", width = 1500, height = 1000, res=220)
fviz_dend(
  hc.ward,
  k = 4,
  cex = 0.3,
  palette = "jco",
  color_labels_by_k = TRUE,
  rect = TRUE,
  rect_fill = TRUE,
  rect_border = "jco",
  labels_track_height = 3.5
)
dev.off()

# hc_label<-cutree(hc.ward, k = 3)
# table(hc_label,label)
# adjustedRandIndex(hc_label, label)
```

### Complete
```{r}
hc.complete <- hclust(d = row_distance_p, method = "complete")

png("/Users/czang/Documents/2020Fall/2079ML/project/BIOST2079/output/hierchical_complete_pearson_4cluster_z.png", width = 1500, height = 1000, res=220)

fviz_dend(
  hc.complete,
  k = 4,
  cex = 0.2,
  palette = "jco",
  color_labels_by_k = TRUE,
  rect = TRUE,
  rect_fill = TRUE,
  rect_border = "jco"
)
dev.off()
```

### Average
```{r}
hc.average <- hclust(d = row_distance_p, method = "average")

png("/Users/czang/Documents/2020Fall/2079ML/project/BIOST2079/output/hierchical_average_pearson_4cluster_z.png", width = 1500, height = 1000, res=220)

fviz_dend(
  hc.average,
  k = 4,
  cex = 0.2,
  palette = "jco",
  color_labels_by_k = TRUE,
  rect = TRUE,
  rect_fill = TRUE,
  rect_border = "jco"
)
dev.off()
```

### Single
```{r}
hc.single <- hclust(d = row_distance, method = "single")
png("/Users/czang/Documents/2020Fall/2079ML/project/BIOST2079/output/hierchical_single_euclidean_4cluster.png", width = 1500, height = 1000, res=220)
fviz_dend(
  hc.single,
  k = 4,
  cex = 0.2,
 # palette = "jco",
  color_labels_by_k = TRUE,
  rect = TRUE,
  rect_fill = TRUE,
  rect_border = "jco",
  labels_track_height = 3
)
dev.off()
```

### Centroid
```{r}
hc.centroid <- hclust(d = row_distance, method = "centroid")

png("/Users/czang/Documents/2020Fall/2079ML/project/BIOST2079/output/hierchical_centroid_euclidean_4cluster.png", width = 1500, height = 1000, res=220)
fviz_dend(
  hc.centroid,
  k = 4,
  cex = 0.2,
  palette = "jco",
  color_labels_by_k = TRUE,
  rect = TRUE,
  rect_fill = TRUE,
  rect_border = "jco",
  labels_track_height = 3
)
dev.off()
```

# Guassian mixture clustering 
```{r}
library(mclust)
?mclustModelNames
fit = Mclust(matrix, G=1:9, modelNames="EII")
summary(fit)

# bic for selected model
fit$bic 
# The optimal number of mixture components (K)
fit$G 

#evaluation
mix_label <- fit$classification
table(mix_label, label)
adjustedRandIndex(mix_label, label)
```

